export const cities =  [  
  {"label":"北京Beijing010","name":"北京","pinyin":"Beijing","zip":"010"},  
  {"label":"重庆Chongqing023","name":"重庆","pinyin":"Chongqing","zip":"023"},  
  {"label":"上海Shanghai021","name":"上海","pinyin":"Changhai","zip":"021"}, 
  { "label": "北京Beijing010", "name": "北京", "pinyin": "Deijing", "zip": "010" },
  { "label": "重庆Chongqing023", "name": "重庆", "pinyin": "Ehongqing", "zip": "023" },
  { "label": "上海Shanghai021", "name": "上海", "pinyin": "Fhanghai", "zip": "021" }, 
  { "label": "北京Beijing010", "name": "北京", "pinyin": "Geijing", "zip": "010" },
  { "label": "重庆Chongqing023", "name": "重庆", "pinyin": "Hhongqing", "zip": "023" },
  { "label": "上海Shanghai021", "name": "上海", "pinyin": "Ihanghai", "zip": "021" }, 
  { "label": "北京Beijing010", "name": "北京", "pinyin": "Geijing", "zip": "010" },
  { "label": "重庆Chongqing023", "name": "重庆", "pinyin": "Khongqing", "zip": "023" },
  { "label": "上海Shanghai021", "name": "上海", "pinyin": "Lhanghai", "zip": "021" }, 
  { "label": "北京Beijing010", "name": "北京", "pinyin": "Meijing", "zip": "010" },
  { "label": "重庆Chongqing023", "name": "重庆", "pinyin": "Nhongqing", "zip": "023" },
  { "label": "上海Shanghai021", "name": "上海", "pinyin": "Ohanghai", "zip": "021" }, 
  { "label": "重庆Chongqing023", "name": "重庆", "pinyin": "Phongqing", "zip": "023" },
  { "label": "上海Shanghai021", "name": "上海", "pinyin": "Qhanghai", "zip": "021" },
  { "label": "北京Beijing010", "name": "北京", "pinyin": "Reijing", "zip": "010" },
  { "label": "重庆Chongqing023", "name": "重庆", "pinyin": "Shongqing", "zip": "023" },
  { "label": "上海Shanghai021", "name": "上海", "pinyin": "Thanghai", "zip": "021" },
  { "label": "北京Beijing010", "name": "北京", "pinyin": "Ueijing", "zip": "010" },
  { "label": "重庆Chongqing023", "name": "重庆", "pinyin": "Vhongqing", "zip": "023" },
  { "label": "上海Shanghai021", "name": "上海", "pinyin": "Whanghai", "zip": "021" },
  { "label": "北京Beijing010", "name": "北京", "pinyin": "Xeijing", "zip": "010" },
  { "label": "重庆Chongqing023", "name": "重庆", "pinyin": "Yhongqing", "zip": "023" },
  { "label": "上海Shanghai021", "name": "上海", "pinyin": "Zhanghai", "zip": "021" }, 
  ];